Serilog:
  Using: [ "Serilog.Sinks.Console" ]
  MinimumLevel:
    Default: "Information"
    Override:
      Microsoft: "Warning"
      Microsoft.Hosting.Lifetime: "Information"
      Microsoft.AspNetCore: "Warning"

  WriteTo:
    - Name: Console
      Args:
        OutputTemplate: "[{Timestamp:HH:mm:ss} {Level:u3} {SourceContext}] {Message:lj}{NewLine}{Exception}"

  Enrich: [ "FromLogContext" ]

AllowedHosts: "*"

Site:
  ExternalStyleSheets:
    - https://raw.githubusercontent.com/Sector-Umbra/sector-umbra.net/refs/heads/main/src/styles/layout.css
    - https://raw.githubusercontent.com/Sector-Umbra/sector-umbra.net/refs/heads/main/src/styles/base.css