// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SU.Replays.Database;

#nullable disable

namespace SUReplays.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250103115912_InitalMigration")]
    partial class InitalMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("SU.Replays.Database.Models.Replay", b =>
                {
                    b.Property<string>("FileLocation")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Participants")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FileLocation");

                    b.ToTable("Replays");
                });
#pragma warning restore 612, 618
        }
    }
}
